### ISSUE TITLE
Link of the book Advanced R on your website

### ISSUE THREAD

**Issue by ChuliangXiao** [hadley/adv-r#1046]
> **Advanced R** helps you master R as a programming language, teaching you what makes R tick. 

I see the book **Advanced R** on you website http://hadley.nz is still linked to 
http://adv-r.had.co.nz/, while http://adv-r.hadley.nz is updated.

**Comment by hadley** [comment]
Fixed, thanks!

**Comment by dandermotj** [comment]
Just wanted to note that pretty much every time I google for sections of Advanced R, the top results are for pages on http://adv-r.had.co.nz/ rather than the latest site. It seems the adv-r.hadley.nz doesn't surface well when googled. I invariably end up going to the Github page first and clicking the link there. Just raising this as potentially confusing for new readers and R users.
