### ISSUE TITLE
Typo in Environments basics

### ISSUE THREAD

**Issue by erocoar** [hadley/adv-r#1160]
In Environments: Environments Basics, I think the figures do not correspond to the code here

https://i.imgur.com/jvPlqkz.png

But it should rather be `e$a <- ...`? 

I can make a pull request for this if I am not mistaken

**Comment by adelenelai** [comment]
Hi @erocoar, I also thought this initially....assuming the figures are correct, could it be that `e$b` points to `e$a`? because of the assignment `e$b <- "a"`? 

If yes, this basically means we have to be careful if we want names to point to strings. Here, "a" is not a string, but is the object `a` itself.

**Comment by hadley** [comment]
No, it was definitely an error in the picture.

**Comment by adelenelai** [comment]
@hadley thanks for clarifying. 

So, in the second picture, `e$a` should continue pointing to `FALSE` and `e$b` should point to the same '123' which `e$d` points to, whereas in the third picture, `e$b` should point to the second set of '123' while `e$a` continues to point to`FALSE`.
