### ISSUE TITLE
Scary example re: FOs and laziness doesn't actually scare

### ISSUE THREAD

**Issue by jennybc** [hadley/adv-r#740]
Re: the laziness subsection of the functional operators chapter.

This is closest anchor:
http://adv-r.had.co.nz/Function-operators.html#behavioural-fos

Text says: "In the following example, we take a list of functions and delay each one. But when we try to evaluate the mean, we get the sum instead."

But that's not what actually happens.

```
funs <- list(mean = mean, sum = sum)
funs_m <- lapply(funs, delay_by, delay = 0.1)

funs_m$mean(1:10)
#> [1] 5.5
```

I don't know if sometimes bad things actually do happen here? Or if maybe a different example would be more reliably frightening.

**Comment by bingtangben** [comment]
The example works before R 3.2.0. After R 3.2.0, higher order functions force arguments.

Higher order functions such as the apply functions and Reduce() now force arguments to the functions they apply in order to eliminate undesirable interactions between lazy evaluation and variable capture in closures.
