### ISSUE TITLE
Lazy evaluation example with lapply is out of date

### ISSUE THREAD

**Issue by expersso** [hadley/adv-r#803]
This example of problems with lazy evaluation (in Functions.Rmd) no longer works, since `lapply` has been changed to deal with this behavior:

```
add <- function(x) {
  function(y) x + y
}
adders <- lapply(1:10, add)
adders[[1]](10)
adders[[10]](10)
```

**Comment by hadley** [comment]
Already been fixed in the dev version http://adv-r.hadley.nz

**Comment by yutannihilation** [comment]
@hadley 
What do you mean by "fixed"? In this part, you tried to "fix" the lazy behavior of `lapply()` by introducing `force()`. But, since `lapply()` has been fixed in the upstream (and "somehow works" now, as you said on https://github.com/hadley/purrr/issues/191#issue-148382132), you don't need to use `force()` anymore.

Yes, in [the chapter of "Functions"](http://adv-r.hadley.nz/functions.html#lazy-evaluation), the result of `adders[[1]](10)`, which was `20` in the printed version of book, is not outdated.

```r
add <- function(x) {
  function(y) x + y
}
adders <- lapply(1:10, add)
adders[[1]](10)
#> [1] 11
adders[[10]](10)
#> [1] 20
```

But, the following comment is outdated and inconsistent as `11` is what we wanted.

> `x` is lazily evaluated the first time that you call one of the adder functions. At this point, the loop is complete and the final value of `x` is 10. Therefore all of the adder functions will add 10 on to their input, probably not what you wanted!

@expersso This is your point, right?

**Comment by hadley** [comment]
Oh I could've sworn I fixed that. Anyway I'll resolve when I'm rewriting that chapter. Don't worry that I'll forget as so so many people have complained about it.

**Comment by yutannihilation** [comment]
Sure 👍 

I'm looking forward to seeing how this part will be rewritten. Thanks for your reply!
