### ISSUE TITLE
S3 class/method naming

### ISSUE THREAD

**Issue by patperry** [hadley/adv-r#864]
I didn't see this issue addressed in the current draft, but it's bitten me before:

If two packages use the same name for an S3 class, you can end up with havoc. For example, *corpus* originally called its text class `"text"`, but *grid* also uses `"text"` as a class. *grid* functions broke when I wrote a custom `$.text` function. I've now settled on the convention that I name my S3 classes `{package}_{class}`, e.g. `corpus_text`, `corpus_json`, `corpus_frame`, etc. It's still possible that the names will clash, but it's unlikely.

A similar issue arises if you want people to be able to provide instances of your custom S3 methods. I originally had an `as_corpus` S3 generic function, with implementations for `tm::Corpus` and `quanteda::corpus` types. I changed the name to `as_corpus_frame` to avoid conflicts if *quanteda* ever decides to provide an `as_corpus` S3 generic to go along with its `corpus` class. (If *corpus* and *quanteda* both define an `as_corpus` generic, then it's impossible for a third package to provide implementations for both.)

**Comment by kbenoit** [comment]
I second that! (as the greedy name-grabber responsible for **quanteda**)

We've also seen strange issues with S4 classes, namely that R seems to load the package when it has an object in its global environment that was defined in a specific package. When I start R and the workspace automatically loaded from a previous session includes a sparse matrix from the **Matrix** package, for instance, then the **Matrix** namespace seems to be attached automatically. 

We had to name our (S4) dictionary object class `dictionary2`, for instance, because **rlang** has an object class of the same name.

That's the downside of having class dispatch from generic methods, rather than classes with methods defined inside the class. If the solution is simply careful (unique) nomenclature, then some guidelines for this would be great.

**Comment by krlmlr** [comment]
I'll be using this strategy for pillar: All classes and constructors get a `pillar_` prefix. The classes and especially the subclass constructors have somewhat lengthy names, though.

**Comment by hadley** [comment]
The policy I'm using for vctrs (and will use for future packages) is to ensure that the class name includes the package name (i.e. `vctrs_sclr`, `vctrs_vctr` etc). The constructors (low-level and use-friendly) don't need to include the package name because they are already namespaced (e.g. `vctrs::new_sclr()`).

I'll briefly allude to this policy in the book but it's a bit of an awkward topic since you might argue that it also belongs in R packages. I've filed an issue there so we don't forget about it: https://github.com/hadley/r-pkgs/issues/504
