### ISSUE TITLE
Class/method granularity

### ISSUE THREAD

**Issue by patperry** [hadley/adv-r#865]
There's some confusion/disagreement over the following, at least in the text analysis community:

A variety of packages provide methods for analyzing text. Many of these packages have their own internal representations of text data. Let's say you have text analysis package with a text type `X` and methods `foo()`, `bar()`, and `baz()`. Let's say another package has text type `Y`. If you want your functions to work for both, you can do one of the following:

1) Make `foo()`, `bar()`, and `baz()` generics; provide implementations `foo.X()`, `foo.Y()`,
`bar.X()`, `bar.Y()`, etc. The old version of the `stm::stm()` used this convention.

2) Leave `foo()`, `bar()`, and `baz()` as regular functions. Provide an `as_X()` generic
with implementations `as_X.X()` and `as_X.Y()`. Export this function so that if another package you don't know about defines text representation, `Z`, that package can define `as_X.Z`. Make `foo()`, `bar()`, and `baz()` convert their inputs using `as_X` before processing the text. The current version of `stm::stm()` uses this approach.

3) Leave `foo()`, `bar()`, and `baz()` as regular functions that only accept type `X`. Require the user to call `foo(as_X(y))` if they have `y` of type `Y`.

I strongly prefer option 2), because it makes the functions generic while placing minimal requirements on the argument types. It's also the least error-prone way to structure the code (both from the developer and the user perspective).

It'd be nice to see some discussion of the issue, and discussion of the design trade-offs involved.

**Comment by hadley** [comment]
Yes, I agree that option 2 is the right one, although you still might want to `foo()` generic if representation `Z` supported a radically more performant algorithm.

Unfortunately advanced R isn't the right place for this discussion. In the interests of space and focus, I'm trying to stay focused on just how the OO systems work, rather than going into too much detail about how to use them effectively. (But that is likely to be one of the topics I cover in the tidy tools book which I'll start on once adv-r is done)
