### ISSUE TITLE
Diagrams in Ch. 18 Expressions are not colorblind-friendly

### ISSUE THREAD

**Issue by brianwdavis** [hadley/adv-r#882]
It's very difficult to distinguish the black and purple colors with the light line-weights used. Only when zooming in (as displayed below vs as shown in context) can I easily discern the rounded corners and difference in hue. Please consider more aggressive rounding of the corners and thicker line-weights to differentiate.

![image](https://user-images.githubusercontent.com/13338560/31418228-d4aac224-ae02-11e7-91e0-4e66858695b2.png)

![image](https://user-images.githubusercontent.com/13338560/31418341-85b2348a-ae03-11e7-9e5c-b9d0dfa3128f.png)

**Comment by hadley** [comment]
The hue is strikingly different to me, even at the small size in the image, and it should be even better in a printed book. Let me ask a few others.

**Comment by brianwdavis** [comment]
Perhaps my poor color vision is an outlier, but it's not usually **that** bad compared to others. I'm using a (several years old) Dell LCD monitor at its native resolution. Even when I fiddle with the brightness or contrast settings, it's  difficult for me to distinguish hues with light lineweights like that diagram.

When zooming in using Chrome, I get to just about the size where I would be able to tell the colors apart at 150%, but then the text is enormous.

**Comment by dan87134** [comment]
You can't depend on how an image looks on "your" monitor. There is a wide range of quality in the color management of monitors in the field.

If color or line width is supposed to convey info make both obvious, don't be subtle at all.

High res monitors often do a poor job of fine lines because, in effect, they make the lines finer than what they look like on a standard res monitor.

Printed materials use a different color gamut, CMYK, than the ones used on computer monitors. The result is an image using CMYK will appear to be muted, i.e. less bright, than one using a typical color gamut for a computer monitor like sRGB. The printed page just can't show the range of colors a computer monitor can.

Ask your printer if you can use sRGB in your images (you probably can) and then use something like Photoshop to see what they will look like after the printer converts them, (think reduces them... CMYK cannot represent all the colors on a computer screen).

That way you will end up with good images for the online version of the book.

The image below is an example of what happens when easy to recognize colors on a monitor are converted to CMYK (I used Photoshop to simulate the conversion. Photoshop can also be used to simulate what color blind people will see, those differences are really dramatic.) If you don't see a difference your monitor may need some adjustment...

Actually it also shows (the image on the right) what the on line version will look like if you publish CMYK colors on the web. Pretty dull, huh? :-)

![parsetree](https://user-images.githubusercontent.com/22779142/32136909-cdb3a2ca-bbe4-11e7-8d21-1d93131903ec.jpg)
