### ISSUE TITLE
Section 4.3.1 Does not modify in place

### ISSUE THREAD

**Issue by actuarialvoodoo** [hadley/adv-r#995]
The last paragraph in this section states that after y has been copied when it was modified that further modifications will be done in the same memory location. However, when I ran this code on my own computer it appears to copy the object y refers to.

``` r
library(lobstr)

x <- 1:3
y <- x

#expect to see x and y at same memory location
obj_addr(x)
#> [1] "0x7fc2cdeb1748"
obj_addr(y)
#> [1] "0x7fc2cdeb1748"

# set up tracemem
cat(tracemem(x), '\n')
#> <0x7fc2cdeb1748>

#expect to see object copied to a new location and then modified
y[[3]] <- 4
#> tracemem[0x7fc2cdeb1748 -> 0x7fc2ca5fa7c8]: eval eval withVisible withCallingHandlers doTryCatch tryCatchOne tryCatchList tryCatch try handle timing_fn evaluate_call evaluate in_dir block_exec call_block process_group.block process_group withCallingHandlers process_file <Anonymous> <Anonymous> <Anonymous> <Anonymous> do.call saveRDS withCallingHandlers 
#> tracemem[0x7fc2ca5fa7c8 -> 0x7fc2cd65f450]: eval eval withVisible withCallingHandlers doTryCatch tryCatchOne tryCatchList tryCatch try handle timing_fn evaluate_call evaluate in_dir block_exec call_block process_group.block process_group withCallingHandlers process_file <Anonymous> <Anonymous> <Anonymous> <Anonymous> do.call saveRDS withCallingHandlers
obj_addr(x)
#> [1] "0x7fc2cdeb1748"
obj_addr(y)
#> [1] "0x7fc2cd65f450"

#expect y to now be modified in place
y[[3]] <- 7
#> tracemem[0x7fc2cd65f450 -> 0x7fc2ce041a00]: eval eval withVisible withCallingHandlers doTryCatch tryCatchOne tryCatchList tryCatch try handle timing_fn evaluate_call evaluate in_dir block_exec call_block process_group.block process_group withCallingHandlers process_file <Anonymous> <Anonymous> <Anonymous> <Anonymous> do.call saveRDS withCallingHandlers
obj_addr(y)
#> [1] "0x7fc2ce041a00"
```

**Comment by hadley** [comment]
Are you using RStudio?

**Comment by actuarialvoodoo** [comment]
Yes, Version 1.1.383

**Comment by actuarialvoodoo** [comment]
I reran my reprex on my work pc this morning with the same result 

Rstudio version 1.1.383
 
SessionInfo:
R version 3.4.2 (2017-09-28)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] lobstr_0.0.0.9000

loaded via a namespace (and not attached):
 [1] compiler_3.4.2  httr_1.3.1      R6_2.2.2        tools_3.4.2     withr_2.1.1    
 [6] curl_3.0        yaml_2.1.15     Rcpp_0.12.16    memoise_1.1.0   git2r_0.19.0   
[11] digest_0.6.12   rlang_0.2.0     devtools_1.13.4

**Comment by hadley** [comment]
(Please don't include session info unless it's explicitly asked for, or you've used `reprex::reprex(..., si = TRUE)` to hide it away. I've deleted it from your issue to avoid cluttering up the discussion)

**Comment by hadley** [comment]
The problem is your your use of `obj_addr()`: it's a function call so will increment the reference count, meaning that it can no longer be modified in place.

```
``` r
x <- 1:3
cat(tracemem(x), '\n')
#> <0x7faffa713b48>

y <- x

y[[3]] <- 4
#> tracemem[0x7faffa713b48 -> 0x7faff5f4d8d8]: eval eval withVisible withCallingHandlers doTryCatch tryCatchOne tryCatchList tryCatch try handle timing_fn evaluate_call <Anonymous> evaluate in_dir block_exec call_block process_group.block process_group withCallingHandlers process_file <Anonymous> <Anonymous> <Anonymous> <Anonymous> do.call saveRDS withCallingHandlers 
#> tracemem[0x7faff5f4d8d8 -> 0x7faffb88f518]: eval eval withVisible withCallingHandlers doTryCatch tryCatchOne tryCatchList tryCatch try handle timing_fn evaluate_call <Anonymous> evaluate in_dir block_exec call_block process_group.block process_group withCallingHandlers process_file <Anonymous> <Anonymous> <Anonymous> <Anonymous> do.call saveRDS withCallingHandlers
y[[3]] <- 7
```

Created on 2018-03-20 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
